/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.t5_p1;

import com.mycompany.t5_p1.controlador.GeneradorVentasTotales;
import com.mycompany.t5_p1.controlador.AddressJpaController;
import com.mycompany.t5_p1.controlador.DocumentJpaController;
import com.mycompany.t5_p1.controlador.PositionsJpaController;
import com.mycompany.t5_p1.modelo.GeneradorInformeClientes;
import com.mycompany.t5_p1.modelo.GeneradorInformeFacturas;
import com.mycompany.t5_p1.modelo.GeneradorInformeProductos;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author Juanfran
 */
public class MenuApp extends javax.swing.JFrame {
    


    /**
     * Creates new form MenuApp
     */
    private DocumentJpaController djc;
    private AddressJpaController ajc;
    private PositionsJpaController pjc;
    private EntityManagerFactory emf;
   
     
    public MenuApp() {
        emf = Persistence.createEntityManagerFactory("persistence");
        djc = new DocumentJpaController(emf);
        ajc = new AddressJpaController(emf);
        pjc = new PositionsJpaController(emf);
        initComponents();
        setLocationRelativeTo(null);
        this.setBackground(Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jmiListadoFactura = new javax.swing.JMenuItem();
        jmiVentasTotales = new javax.swing.JMenuItem();
        jmiFacturasCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bill.png"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(204, 255, 255));
        jMenuBar1.setBorder(null);
        jMenuBar1.setOpaque(true);

        jMenu1.setBackground(new java.awt.Color(204, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        jMenu1.setText("Home");

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/file.png"))); // NOI18N
        jMenu3.setText("Informes");

        jmiListadoFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiListadoFactura.setText("Listado Facturas");
        jmiListadoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListadoFacturaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiListadoFactura);

        jmiVentasTotales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiVentasTotales.setText("Ventas Totales");
        jmiVentasTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVentasTotalesActionPerformed(evt);
            }
        });
        jMenu3.add(jmiVentasTotales);

        jmiFacturasCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmiFacturasCliente.setText("Facturas Clientes");
        jmiFacturasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFacturasClienteActionPerformed(evt);
            }
        });
        jMenu3.add(jmiFacturasCliente);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(204, 255, 255));
        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiListadoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListadoFacturaActionPerformed
        GeneradorInformeClientes.leerInforme(ajc.findAddressEntities());
        //GeneradorInformeFacturas.leerInforme(djc.findDocumentEntities());
        //GeneradorInformeProductos.leerInforme(pjc.findPositionsEntities());
    }//GEN-LAST:event_jmiListadoFacturaActionPerformed

    private void jmiFacturasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFacturasClienteActionPerformed
    }//GEN-LAST:event_jmiFacturasClienteActionPerformed

    private void jmiVentasTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVentasTotalesActionPerformed
        ClaseGenerada claseGenerada = new ClaseGenerada(0, "", 0, 0, 0L);
        List<ClaseGenerada> listaGenerada = claseGenerada.conseguirDatos();
        GeneradorVentasTotales.leerInforme(listaGenerada);
    }//GEN-LAST:event_jmiVentasTotalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuApp menu = new MenuApp();
                menu.setLocationRelativeTo(null);
                menu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiFacturasCliente;
    private javax.swing.JMenuItem jmiListadoFactura;
    private javax.swing.JMenuItem jmiVentasTotales;
    // End of variables declaration//GEN-END:variables
}
